export const project_data = [
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Interior Glazing, Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Overture Hamlin',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Jacksonville, FL',
        trade: 'Interior Glazing',
        manager: 'Cody Fisher',
        name: 'Elan Colorado',
        completion_date: 'May 1, 2020',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
    {
        gc: 'Kiewit Corporation',
        location: 'Orlando, FL',
        trade: 'Exterior Glazing',
        manager: 'Theresa Webb',
        name: 'Unity Church',
        completion_date: 'TBD',
    },
]

export const project_table_header = [
    { text: "", value: "icon", sortable: false },
    { text: "GC", value: "gc", width: 250 },
    { text: "Location", value: "location", width: 200 },
    { text: "Trade", value: "trade", width: 250 },
    { text: "Manager", value: "manager", width: 180 },
    { text: "Project Name", value: "name", width: 180 },
    { text: "Completion Date", value: "completion_date", width: 180 },
    { text: "Project Type", value: "project_type", width: 130 },
    { text: "Owner", value: "owner", width: 200 },
    { text: "Project Value", value: "value", width: 130 },
    { text: "Sub Tier Contractors", value: "sub_contractors", width: 400  },
    { text: "Status", value: "status", width: 130 },
    { text: "Gross Sq. Ft.", value: "square_feet", width: 140 },
    { text: "Notes", value: "notes", width: 500 },
]
